# Generated by Django 3.2.18 on 2023-10-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeedetectiontimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image2'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image3'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_image4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image4'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_image5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image5'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_image6',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image6'),
        ),
    ]
